//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DashboardMessage.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MID { get; set; }
        public string Title { get; set; }
        public string Message1 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Uid { get; set; }
        public string Reply { get; set; }
    
        public virtual User User { get; set; }
    }
}
