//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolPerfectProject.App_Data
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class image
    {
        public int ID { get; set; }
        public string imageurl { get; set; }
        public HttpPostedFileBase UploadImage { get; set; }
    }
}
