// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lab3.NetCoreLec3.Data;

#nullable disable

namespace lab3.NetCoreLec3.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20220707114425_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("lab3.NetCoreLec3.Models.Course", b =>
                {
                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LabHours")
                        .HasColumnType("int");

                    b.Property<int>("LecHours")
                        .HasColumnType("int");

                    b.HasKey("CID");

                    b.ToTable("courses");
                });

            modelBuilder.Entity("lab3.NetCoreLec3.Models.Department", b =>
                {
                    b.Property<int>("deptID")
                        .HasColumnType("int");

                    b.Property<string>("departmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deptID");

                    b.ToTable("departments");
                });

            modelBuilder.Entity("lab3.NetCoreLec3.Models.Student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("DeptID")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<string>("imagepath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.HasIndex("DeptID");

                    b.ToTable("students");
                });

            modelBuilder.Entity("lab3.NetCoreLec3.Models.StudentCourse", b =>
                {
                    b.Property<int>("Sid")
                        .HasColumnType("int");

                    b.Property<int>("CID")
                        .HasColumnType("int");

                    b.Property<int>("degree")
                        .HasColumnType("int");

                    b.HasKey("Sid", "CID");

                    b.HasIndex("CID");

                    b.ToTable("studentCourses");
                });

            modelBuilder.Entity("lab3.NetCoreLec3.Models.Student", b =>
                {
                    b.HasOne("lab3.NetCoreLec3.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DeptID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("lab3.NetCoreLec3.Models.StudentCourse", b =>
                {
                    b.HasOne("lab3.NetCoreLec3.Models.Course", "course")
                        .WithMany()
                        .HasForeignKey("CID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("lab3.NetCoreLec3.Models.Student", "student")
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("course");

                    b.Navigation("student");
                });
#pragma warning restore 612, 618
        }
    }
}
